usb-storage: Cleanup LV.AU.0.0.1-13310-gen3meta.0 mismerge
Properly reconcile the following commits
98ada19 ("usb-storage: Revert commit 747668dbc061 ("usb-storage: Set virt_boundary_mask to avoid SG overflows")")
a311892 ("usb-storage: Set virt_boundary_mask to avoid SG overflows")

This silences the following compilation error:

../drivers/usb/storage/scsiglue.c:96:2: error: use of undeclared identifier 'maxp'
        maxp = usb_maxpacket(us->pusb_dev, us->recv_bulk_pipe, 0);
        ^
../drivers/usb/storage/scsiglue.c:97:47: error: use of undeclared identifier 'maxp'
        blk_queue_virt_boundary(sdev->request_queue, maxp - 1);
                                                     ^
Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>